### PR TITLE
sm.6: Fix clock example for copy'n'paste

### PR DESCRIPTION
**Pull request by hartwork**
Before (note the quotes, man-db 2.12.0):
```
(while sleep 1; do date +%T; printf ’\f’; done) | sm -
```

After:
```
(while sleep 1; do date +%T; printf \\f; done) | sm -
```

### CODE REVIEW

**Comment by hartwork** [comment]
@nomeata thanks for the merge! I maintain the [Gentoo packaging of screen-message](https://packages.gentoo.org/packages/x11-misc/screen-message) and I love the tool, great job. Is there a chance you could release 0.27 with this pull request merged so I can push the fixed man page to Gentoo users in a clean way?

**Comment by nomeata** [comment]
Let me try, haven’t done it in a while :-)

**Comment by nomeata** [comment]
Do you actually need a tarball or can you fetch the release from github?

**Comment by hartwork** [comment]
@nomeata I can fetch the tarball and run `autoreconf` but there is something broken in the makefile due to a file move in 7ac5c5cd5304dcf462c0143d6273d4bd4426bbc1. Let me have a closer look, maybe I can do a pull request on that or make it a proper report as a new issue at least.

**Comment by nomeata** [comment]
Should have tried 🤦🏻 . Thanks for having a look!

**Comment by hartwork** [comment]
> Should have tried 🤦🏻 . Thanks for having a look!

Created issue #16 now. (My vote for also adding simple GitHub Actions CI after a fix.)

**Comment by hartwork** [comment]
@nomeata I created pull request #17 with a fix now, please test locally before merging. I'm planning on offering CI in a pull request before 02:00 UTC+1 tonight, I think merging that (if found mergable) and then releasing 0.28 would rock.

**Comment by nomeata** [comment]
Much appreciated! I’ll likely be in bed by then, but will merge and release tomorrow then.

**Comment by hartwork** [comment]
@nomeata ready for review now, I hope you like it: #18 :beers:

**Comment by nomeata** [comment]
Great work, thanks. 0.28 tagged and released. Enjoy!

**Comment by hartwork** [comment]
@nomeata glad you like it, bumped to 0.28 in Gentoo now as well: https://github.com/gentoo/gentoo/commit/9be419865c1488f2190d17008914a6c0d55f4b01

**Pull request merged**
